version: "3"
services: 
    node:
        build:
            context: ./node
            dockerfile: Dockerfile
        image: tiagotxm/node_web_app
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
        container_name: node
        tty: true
        networks: 
            - webapp_net
        depends_on: 
            - mysql
            
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: tiagotxm/nginx_web_app
        container_name: nginx
        networks: 
            - webapp_net
        ports:
            - "8080:80"
        depends_on: 
            - node

    mysql:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        restart: always
        tty: true
        volumes: 
            - ./mysql/data:/var/lib/mysql
        image: tiagotxm/mysql_web_app
        container_name: mysql
        environment: 
            - MYSQL_DATABASE=web_app
            - MYSQL_ROOT_PASSWORD=123
        networks:
            - webapp_net


networks:
    webapp_net:
        driver: bridge 